drop table if exists member CASCADE;
     create table member
     (
         id   bigint generated by default as identity,
         name varchar(255),
         primary key (id)
);

drop table if exists category CASCADE;
     create table category
     (
         id   bigint generated by default as identity,
         name varchar(255),
         primary key (id)
);

drop table if exists badge CASCADE;
     create table badge
     (
         id   bigint generated by default as identity,
         name varchar(255),
         primary key (id)
);

drop table if exists product CASCADE;
     create table product
     (
         id   bigint generated by default as identity,
         category_id bigint,
         name varchar(255),
         desc varchar(255),
         price bigint,
         sale_rate float,
         thumbnail_url varchar(255),
         images_id bigint,
         primary key (id)
);

drop table if exists images CASCADE;
     create table images
     (
         id   bigint generated by default as identity,
         product_id bigint,
         category_id bigint,
         image_url varchar(255),
         primary key (id)
);